config/routes.rb
Rails.application.routes.draw do

  root to: 'netkeiba#index'
  get 'netkeiba/index'
  post 'netkeiba/predict'

  get 'horses/addPage'
  resources :horses, only: [:index, :show, :create, :destroy]

end

app/models/horse.rb
class Horse < ActiveRecord::Base
  has_many :race_results


end

app/models/race_result.rb
class RaceResult < ActiveRecord::Base
  belongs_to :horse
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: [:show, :destory]
  def index
    @horses = Horse.all
  end

  def show
    @results = @horse.race_results
    # うまくいかねw
    # respond_to do |format|
    #   format.html {}
    #   format.csv { render "horses/show.csv",location: [@results, @horse]}
    # end
  end

  def create
    crawler = Crawler.new()
    crawler.start(url_params[:url])
    @horse = Horse.create(crawler.getHorseProfile)
    crawler.getRaceResults.each do |result|
      @horse.race_results.create(result)
    end
    render action: 'show', status: :created, location: @horse
  end

  def destroy
    @horse.destroy
    redirect_to horses_url
    
  end

  private
    def url_params
      params.require(:post).permit(:url)
    end
    def set_horse
      @horse = Horse.find(params[:id])
    end
end

app/controllers/netkeiba_controller.rb
class NetkeibaController < ApplicationController
  def index
    @horses = Horse.all
  end

  def predict
    @raseHorses
    @ranking =[]
  end

  private
    def horses_params
      params.require(:post).permit(horses: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/netkeiba_helper.rb
module NetkeibaHelper
end

app/views/horses/addPage.html.erb
<h1>競走馬の追加</h1>
<%= form_tag horses_path do %>
  <div class="field">
    <%= label :post, "Horse URL" %>
    <%= text_field :post, :url %>  
  </div>
  <%= submit_tag "Get Horse Data" %>
<% end %>

app/views/horses/index.html.erb
<h1>競馬データベース</h1>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @horses.each do |horse| %>
      <tr>
        <td><%= link_to(horse.name, horse) %></td>
        <td><%= link_to("WEB", "http://db.netkeiba.com/horse/#{horse.horse_id}") %></td>
        <td><%= link_to("Destroy", method: :delete , data: { confirm: 'Are you sure? '} ) %></td>
        <td><%= link_to("csv ", params.merge(format: :csv)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/horses/show.html.erb
<h1>Horses#show</h1>
<h2><%= @horse.name %> <%= button_to("csv", params.merge(format: :csv), method: :get ,class: "btn btn-success") %></h2>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
    <% @results.attribute_names.each do |name| %>
      <th><%= name %></th>
    <% end %>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |result| %>
      <tr>
        <% result.attributes.values_at(*@results.attribute_names).each do |d| %>
          <td> <%= d %> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_sidebar.html.erb
 <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="/">
                    Ansible GUI
                </a>
            </li>
            <li>
                <a href="/">Home</a>
            </li>
            <li>
                <%= link_to 'Horses',horses_path %>
            </li>
            <li>
                <%= link_to 'Add data', horses_addPage_path %>
            </li>
            <li>
                <%= link_to 'How To', "" %>
            </li>
            <li>
        		<%= link_to 'About', "" %>
            </li>
            <li>
        		<%= link_to 'Contact', "" %>
            </li>
        </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Netkeiba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
  <%= render 'layouts/sidebar' %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      
      <%= yield %>

    </div>
  </div>
  
</div>

</body>
</html>

app/views/netkeiba/index.html.erb
<h1>競馬予想</h1>

<%= form_tag netkeiba_predict_path do %>
  <% for i in 1..18 %>
    <div class="field">
      <%= label :horses, "Please input horse id in Lane #{i}" %>
      <%= text_field_tag 'horses[]' %>
    </div>
  <% end %>
  <%= submit_tag "Predict" %>
<% end %>

<h2> サイトURLで自動化したい（レースID） </h2>

app/views/netkeiba/predict.html.erb
<h1>予想結果</h1>
<% i = 0 %>
<% !@ranking.empty? && @ranking.each do |horse| %>
  <h2><%= "第#{i}位　　　" %><%= link_to(horse.name , horse ) %>　</h2>
<% end %>

<%= link_to("back", root_path ) %>